[package]
name = "rust-study"
version = "0.1.0"
edition = "2024"

[workspace]
name = "rust-study"
members = ["rust_basic", "rust_async", "rust_net"]

[dependencies]
duct = "1.0.0"
serde = {version="1.0", features = ["derive"]}
serde_json = "1.0.142"
rust-ini = "0.21"