receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 3s
    send_batch_size: 64
  filter/sampling:
    error_mode: ignore
    logs:
      log_record:
        # DEBUG级别日志采样1% - 使用trace_id的最后几位实现采样
        - 'severity_text == "DEBUG" and Substring(trace_id.string, 30, 2) == "00"'
        # INFO级别日志采样10% - 使用trace_id的最后一位实现采样
        - 'severity_text == "INFO" and Substring(trace_id.string, 31, 1) == "0"'
        # WARN级别日志采样20% - 使用trace_id的最后一位实现采样
        - 'severity_text == "WARN" and (Substring(trace_id.string, 31, 1) == "0" or Substring(trace_id.string, 31, 1) == "1")'
        # ERROR级别日志采样50% - 使用trace_id的最后一位实现采样
        - 'severity_text == "ERROR" and (Substring(trace_id.string, 31, 1) == "0" or Substring(trace_id.string, 31, 1) == "1" or Substring(trace_id.string, 31, 1) == "2" or Substring(trace_id.string, 31, 1) == "3" or Substring(trace_id.string, 31, 1) == "4")'
        # FATAL级别日志采样100%
        - 'severity_text == "FATAL"'
        # 处理数字形式的严重级别
        # DEBUG (5-9)
        - 'severity_number >= 5 and severity_number <= 9 and Substring(trace_id.string, 30, 2) == "00"'
        # INFO (9-13)
        - 'severity_number >= 9 and severity_number <= 13 and Substring(trace_id.string, 31, 1) == "0"'
        # WARN (13-17)
        - 'severity_number >= 13 and severity_number <= 17 and (Substring(trace_id.string, 31, 1) == "0" or Substring(trace_id.string, 31, 1) == "1")'
        # ERROR (17-21)
        - 'severity_number >= 17 and severity_number <= 21 and (Substring(trace_id.string, 31, 1) == "0" or Substring(trace_id.string, 31, 1) == "1" or Substring(trace_id.string, 31, 1) == "2" or Substring(trace_id.string, 31, 1) == "3" or Substring(trace_id.string, 31, 1) == "4")'
        # FATAL (21+)
        - 'severity_number >= 21'

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch,filter/sampling]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]