//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::city::Entity as City;
pub use super::dict::Entity as Dict;
pub use super::dict_group::Entity as DictGroup;
pub use super::driving_school::Entity as DrivingSchool;
pub use super::question::Entity as Question;
