//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "question")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub question: String,
    pub options: Json,
    pub answer: String,
    pub question_category: i32,
    pub case_category: i32,
    pub image: Option<String>,
    pub description: Option<String>,
    pub create_time: Option<Date>,
    pub update_time: Option<Date>,
    pub create_by: Option<String>,
    pub update_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
