import { Button, VerticalBox, CheckBox, ComboBox, GridBox, ListView, StandardListView, Slider } from "std-widgets.slint";
import { Calendar } from "./components/calendar.slint";
import { Separate } from "./components/separate.slint";
import { TodoList } from "./components/todoList.slint";
import { Tarbbar } from "./components/tarbbar.slint";

import {Logic, A} from "./global/logic.slint";
import {User, Sex} from "./global/user.slint";
export { Logic, User, Sex, A }

// import { 
//     AppBar, BottomAppBar,LargeAppBar,SearchBar,
//     FilledButton,ElevatedCard,CheckBox,CheckState,CheckBoxTile,
//     ActionChip,Dialog,DropDownMenu
// } from "./material-1.0/material.slint";


// export component AppWindow inherits Window {
//     title: "Daily To-Do";
//     width: 400px;
//     height: 700px;
//     background: @linear-gradient(180deg,#f2f2f2 0%, #ffffff 100%);  // 从上到下的白色到灰色渐变
    
//     // 暴露Calendar组件的current-weekday属性
//     in property <string> current-weekday;

//     VerticalLayout {
//         spacing: 20px;
//         VerticalLayout {
//             spacing: 55px;
//             Rectangle {
//                 width: 100%;
//                 height: 150px;
//                 background: #68a8ab;
//                 border-bottom-left-radius: 20px;
//                 border-bottom-right-radius: 20px;
//                 calendar := Calendar {
//                     x: parent.width * 0.05;
//                     y: parent.height * 0.2;
//                     width: parent.width * 0.9;
//                     current-weekday: root.current-weekday;
//                 }
//             }
//             Separate {
//                 width: 100%;
//             }
//         }
//         TodoList {
//         }
//     }
    
//     Tarbbar {
//         y: (parent.height - self.height);
//         height: 40px;
//         width: parent.width;
//     }
// }

// =====================================================Surrealism UI 组件====================================================
import { SText, SButton, SDivider, SCard, STag,SCollection,SMenu } from "./surrealism-ui/index.slint";
import { Themes } from "./surrealism-ui/use/index.slint";
export component AppWindow inherits Window {
    title: "Daily To-Do";
    width: 400px;
    height: 700px;

    VerticalBox {
        spacing: 10px;
        SText {
            color: #f60;
            text: "use special color";
        }
        SButton {
            round: true;
            text: "Save";
            clicked => {
                self.text = "clicked";
            }
        }
        SDivider {
            width: 380px;
            height: 1px;
        }
        SCard {
            card-height: 36px;
            card-width: 168px;
            theme: Light;
            Text{
                text: "SCard";
            }
        }
        STag {
            text:"error!";
            theme: Themes.Error;
        }
        c:=SCollection{
            height: 180px;
            width: 180px;
            scale : 3;
            clicked => {
                c.scale = c.is-scale ? c.scale / 3 : c.scale * 3;
                txt.font-size = self.toggle(txt.font-size, 1.5);
                btn.width = self.toggle(btn.width, 1.6);
                btn.theme = c.is-scale ? Themes.Dark : Themes.Error;
            }
            VerticalLayout {
            padding: 20px;
            spacing: 20px;
            alignment: center;
            Rectangle {
                txt:=SText {
                text:"Surrealism";
                }
            }
            Rectangle {
                btn:=SButton{
                }
            }
            }
        }
        Rectangle {
            height:200px;
            width: menu.width;
            
            menu:=SMenu {
                more-width :180px;
                theme: Themes.Dark;
                change(index,item)=>{
                debug(index);
                debug(item);
                }
            }
        }
    }
}

// =====================================================Material Design组件====================================================
// export component AppWindow inherits Window {
//     width: 400px;
//     background: transparent;
//     VerticalLayout {
//         spacing: 20px;
//         // 顶部栏
//         AppBar {
//             title: "My App";
//             width: parent.width;
//             height: 50px;
//         }
//         // 底部栏
//         BottomAppBar {
//             width: parent.width;
//             height: 80px;
//             icon-buttons: [
//                 { icon: @image-url("../icons/share.svg"), tooltip: "Home", enabled: true },
//                 { icon: @image-url("../icons/search.svg"), tooltip: "Search", enabled: true }
//             ];
//             fab-icon: @image-url("../icons/add.svg");
//         }
//         LargeAppBar {
//             title: "My App";
//             width: parent.width;
//             height: 50px;
//         }
//         // 搜索栏
//         SearchBar {
//             placeholder-text: "Search...";
//             width: 280px;
//             height: 56px;
//         }
//         FilledButton {
//             text: "Click me";
//             width: 120px;
//             height: 40px;
//         }
//         ElevatedCard {
//             width: 200px;
//             height: 150px;
//             clickable: true;
//             Text {
//                 text: "Elevated Card";
//             }
//         }
//         CheckBox {
//             check-state: CheckState.checked;
//         }
//         CheckBoxTile {
//             text: "Option 1";
//             check-state: CheckState.checked;
//         }
//         ActionChip {
//             text: "Action";
//             icon: @image-url("../icons/add.svg");
//             width: 100px;
//             height: 32px;
//         }
//         Dialog {
//             title: "Confirm Action";
//             default-action-text: "OK";
//             actions: ["Cancel"];
//         }
//         DropDownMenu {
//             width: 280px;
//             height: 50px;
//             items: [
//             { text: "Copy" },
//             { text: "Cut" },
//             { text: "Paste" },
//             ];
//         }
//     }
// }