[package]
name = "rust_wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "27.0"

winit = "0.30.12"
# raw-window-handle = "0.6.2"

# Floem 支持 Windows、macOS 和 Linux，并使用 wgpu 进行渲染。如果 GPU 不可用，则将使用由 tiny-skia 驱动的 CPU 渲染器。
floem = "0.2.0"


lilt = "0.8.1"
# glyphon = "0.9.0"
rfd = "0.15.4"