import {Logic} from "../global/logic.slint";
import { Button } from "std-widgets.slint";
export component Tarbbar {

    Rectangle {
        width: 100%;
        height: 50px;
        background: #68a8ab;
        
        Button {
            width: 80px;
            height: parent.height - 20px;
            text: "+";
            clicked => {
                Logic.count = Logic.magic_operation(Logic.count);
            }
        }
    }
    
}