
export component TodoList {
    
    HorizontalLayout {
        alignment: center;
        
        VerticalLayout {
            spacing: 10px;
            Rectangle {
                width: root.width * 0.9;
                height: 80px;
                background: #ffffff;
                border-radius: 5px;
                drop-shadow-blur: 10px;
                drop-shadow-color: #9c9c9c;
                drop-shadow-offset-x: 0px;
                drop-shadow-offset-y: 0px;
            }

            Rectangle {
                width: root.width * 0.9;
                height: 80px;
                background: #ffffff;
                border-radius: 5px;
                drop-shadow-blur: 10px;
                drop-shadow-color: #9c9c9c;
                drop-shadow-offset-x: 0px;
                drop-shadow-offset-y: 0px;
            }
        }
    }

}